"""
This file loads the mdtMainWindow file and connects it to events.
It is necessary, as the mdtMainWindow file is only generated by pyuic
and overwrites all the changes made inside as soon as changes to the UI
are made.
"""
from ui.mdtMainWindow import Ui_MainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
from utils.database import SQLiteDatabase
import pyqtgraph as qtg


class UIMain(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(UIMain, self).__init__()
        self.setupUi(self)
        self.bloodButton.clicked.connect(self.display_blood)
        self.leftMenuButton.clicked.connect(self.show_menu)
        self.db = None  # SQLite database
        self.db = SQLiteDatabase('/home/nico/Documents/blood_values.db')

        # Plotting
        self.columns = None

    def display_blood(self):
        if self.db is None:
            _database = QtWidgets.QFileDialog.getOpenFileName(self, "Open Database File",
                                                              QtCore.QDir.homePath(), "Database files (*.db)")[0]
            self.db = SQLiteDatabase(_database)
        values, self.columns = self.db.get_entries_all("blood")
        self.bloodWidget.plot([1,2,3], values["cholesterol"].tolist())
        four = 4

    def show_menu(self):
        four = 4
